// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvfdgluglzlsbaifhuyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2ZmRnbHVnbHpsc2JhaWZodXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjExMTEsImV4cCI6MjA2NjQzNzExMX0.MqxrKfNIcZn5kcsNUku7EhebzGz63Dx2S23pxTG_LOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);